jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # --- ДОДАЙ ЦЕЙ БЛОК ---
    # Всі 'run' команди будуть виконуватися в цій папці
    defaults:
      run:
        working-directory: Lab2 
    # -----------------------

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Тепер всі ці команди автоматично запустяться
      # всередині папки /Lab2
      - name: Build Docker Images
        run: docker compose build

      - name: Run containers in background
        run: docker compose up -d

      - name: Wait for services to start
        run: sleep 15

      - name: Check container logs
        run: docker compose logs

      - name: Stop containers
        run: docker compose down
