name: Find My Files (Diagnostic)

on:
  push:
    branches:
      - main

jobs:
  investigate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List all files and folders
        run: |
          echo "Listing all files from the root:"
          ls -R
