name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Вказуємо, що виконуємо на твоєму AWS сервері
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ВИПРАВЛЕНО: 'docker-compose' з дефісом
      - name: Stop Old Containers
        run: docker-compose down

      # ВИПРАВЛЕНО: 'docker-compose' з дефісом
      - name: Build and Deploy
        run: docker-compose up --build -d

      # Ця команда правильна, бо це не 'compose'
      - name: Clean up old images
        run: docker image prune -af
